import Head from "next/head";
import Image from "next/image";

import ScrollAnimation from "react-animate-on-scroll";

import Navigation from "../components/Navigation";

export default function Home() {
  return (
    <div className="bg-darkpurp">
      <Head>
        <title>Ian Fajardo | Lead, Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div>
        <div className="py-lg-4 text-white bg-darkpurp">
          <div className="container py-lg-5 py-3">
            <div className="row align-items-center">
              <div className="col-lg-8">
                <ScrollAnimation
                  animateIn="fadeInLeft"
                  animateOut="fadeOutLeft"
                  delay={1}
                >
                  <div className="jumbo-container">
                    <div className="d-flex flex-column flex-lg-row align-items-lg-center mb-2 justify-content-start">
                      <h1 className="jumbo-title border-under border-under-alt">
                        {" "}
                        Lead Full Stack Developer
                      </h1>
                    </div>

                    <p className="lead">
                      Hello, I'm{" "}
                      <span className="text-primary fw-bold">Ian Fajardo.</span>
                    </p>

                    <p className="lead">
                      I passionately craft custom{" "}
                      <span className="text-primary fw-bold">
                        web experiences
                      </span>{" "}
                      using innovative solutions.
                    </p>

                    <a
                      href="mailto:hello@ianfajardo.com"
                      className="btn btn-primary me-1"
                    >
                      <i className="fas fa-envelope me-1"></i> Let's Chat{" "}
                    </a>

                    <a
                      href="https://www.behance.net/ianfajardo"
                      className="btn btn-dark me-1"
                    >
                      Portfolio
                    </a>

                    <a
                      href="https://www.linkedin.com/in/arielianfajardo/"
                      className="btn btn-linkedin me-1"
                    >
                      <i className="fab fa-linkedin-in"></i>
                    </a>

                    <a
                      href="https://twitter.com/ianfajardozx"
                      className="btn btn-twitter me-1 text-white"
                    >
                      <i className="fab fa-twitter"></i>
                    </a>
                  </div>
                </ScrollAnimation>
              </div>
              <div className="col-lg-4">
                <ScrollAnimation
                  animateIn="fadeInRight"
                  animateOut="fadeOutRight"
                  delay={1}
                >
                  <img src="headshot-2.jpg" alt="" style={{ width: "100%" }} />
                </ScrollAnimation>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-darkpurp pb-5">
          <ScrollAnimation animateIn="fadeInUp" animateOut="fadeOut">
            <div className="container">
              <div className="border-radius-high  bg-primary p-4 text-white">
                <div className="callout-box">
                  <div className="row align-items-center">
                    <div className="col-lg-9">
                      <div className="d-flex align-items-center">
                        <img
                          src="IFwhite.png"
                          alt="Logo"
                          style={{ width: "6rem" }}
                          className="pe-4"
                        />
                        <div>
                          <h2 className="mt-3">I'm available for freelance work</h2>
                          <div className="lead mb-3">
                            Let me help you with development, design and
                            everything web
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 text-lg-right">
                      <a
                        href="mailto:hello@ianfajardo.com"
                        className="btn btn-darkpurp me-1"
                      >
                        Contact
                      </a>
                      <a
                        href="https://www.behance.net/ianfajardo"
                        className="btn btn-light"
                      >
                        Portfolio
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </ScrollAnimation>
        </div>

        <div id="work" className="work-container bg-darkpurp text-white p-high">
          <ScrollAnimation animateIn="fadeIn" animateOut="fadeOut" delay={1}>
            <div className="container ">
              <div className="row">
                <div className="col-lg-12">
                  <h2 className="display-3 mt-3 mb-3">
                    Design a better web with me.
                  </h2>
                </div>
              </div>

              <div className="row">
                <div className="col-lg-4">
                  <i className="work-icon fas fa-laptop-code mt-5"></i>
                  <h2 className="border-under">Development</h2>
                  <p className="lead-low">
                    I want to make sure we use the right technology to give you
                    the functionality that you need.
                  </p>
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="bg-none card">
                        <div className="card-body">
                          <i className="far fa-file-code"></i> HTML/CSS
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="bg-none card">
                        <div className="card-body">
                          <i className="fab fa-js-square"></i> Javascript
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="bg-none card">
                        <div className="card-body">
                          <i className="fab fa-react"></i> React
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="bg-none card">
                        <div className="card-body">
                          <i className="fab fa-vuejs"></i> Vue
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4">
                  <i className="work-icon fas fa-drafting-compass mt-5"></i>
                  <h2 className="border-under">Design</h2>
                  <p className="lead-low">
                    I'll help craft a unique design for your project to stand
                    out from the crowd while also making sure it's
                    user-friendly.
                  </p>
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="bg-none card">
                        <div className="card-body">
                          <i className="fas fa-mobile-alt"></i> UI/UX
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="bg-none card">
                        <div className="card-body">
                          <i className="fas fa-laptop-code"></i> Web Design
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="col-lg-4">
                  <i className="work-icon fas fa-seedling mt-5"></i>
                  <h2 className="border-under">Planning</h2>
                  <p className="lead-low">
                    Creating a maintainable and evolving application is a step
                    towards continued success.
                  </p>

                  <div className="row">
                    <div className="col-lg-7">
                      <div className="bg-none card mb-2">
                        <div className="card-body">
                          <i className="far fa-file-alt"></i> Documentation
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-5">
                      <div className="bg-none card mb-2">
                        <div className="card-body">
                          <i className="fab fa-searchengin"></i> SEO
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="row mt-5">
                  <div className="col-lg-12">
                    <a
                      href="https://www.behance.net/ianfajardo"
                      className="btn btn-primary btn-lg me-1"
                    >
                      View My Portfolio
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </ScrollAnimation>
        </div>

        <div className="py-5 text-white">
          <div className="container">
            <div className="row">
              <div className="col-lg-8">
                <h2 className="mt-4 border-under">About</h2>
                <p className="mt-2">
                  Currently, Ian Fajardo is a Lead Full Stack Web Developer at
                  the Airlines Reporting Corporation. He passionately crafts
                  custom web experiences with innovative solutions for his
                  customers. In his personal life, he loves doing outdoor
                  activities, kickboxing and snowboarding.
                </p>
              </div>
              <div className="col-lg-4">
                <div className="card bg-primary">
                  <div className="card-body ele-3">
                    <div className="mb-3">Contact</div>
                    <div className="mb-3">
                      <i className="fas fa-envelope me-1"></i>{" "}
                      <a
                        className="text-white"
                        href="mailto:hello@ianfajardo.com"
                      >
                        hello@ianfajardo.com
                      </a>
                    </div>

                    <div className="mb-3">
                      <i className="fab fa-twitter me-1"></i>{" "}
                      <a className="text-white" href="https://twitter.com">
                        @ianfajardozx
                      </a>
                    </div>

                    <div className="mb-3">
                      <i className="fab fa-linkedin-in me-1"></i>{" "}
                      <a
                        className="text-white"
                        href="https://www.linkedin.com/in/arielianfajardo/"
                      >
                        LinkedIn
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="row align-items-center mt-5">
              <div className="col-lg-1">
                <img src="IFred.png" alt="Logo" style={{ width: "50px" }} />
              </div>
              <div className="col-lg-10">
                &copy; Ian Fajardo All rights Reserved
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
