import Head from "next/head";
import Image from "next/image";

import ScrollAnimation from "react-animate-on-scroll";

import Navigation from "../components/Navigation";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import { faCalendar } from "@fortawesome/free-solid-svg-icons";
import { fab } from "@fortawesome/free-brands-svg-icons";
import { faTwitter, faLinkedin } from "@fortawesome/free-brands-svg-icons";
import {
  faEnvelope,
  faLaptopCode,
  faDraftingCompass,
  faSeedling,
  faFileCode,
  faMobileAlt,
  faFileAlt,
  faSearch,
} from "@fortawesome/free-solid-svg-icons";
import Footer from "../components/Footer";

library.add(
  fab,
  faEnvelope,
  faLaptopCode,
  faDraftingCompass,
  faSeedling,
  faFileCode,
  faMobileAlt,
  faFileAlt,
  faSearch
);

var logos = [
  {
    name: "Jade Villa",
    file: "/jade-villa-logo-transparent.png",
    description:
      "Digitized the Jade Villa sign for use with social media and online presence.",
  },
  {
    name: "Hibachi With Us",
    file: "/hibachi-with-us.png",
    description: "A logo designed for hibachi experience brought to your home.",
  },
  {
    name: "Fired Up",
    file: "/hs-firedup-logo-2.png",
    description: "Designed for our church young adult group.",
  },
  {
    name: "Air Force Patch",
    file: "/as-usa-transparent.png",
    description: "",
  },
  {
    name: "High Tide VB",
    file: "/high-tide-logo.png",
    description: "Designed for a local Instagram account and apparel company.",
  },
  {
    name: "Campsite Kit",
    file: "/campsite-kit-white.png",
    description: "",
  },
  {
    name: "Coinupsurge",
    file: "/coinupsurge-square-logo-final.png",
    description: "",
  },
  {
    name: "Stay Breezy",
    file: "/stay-breezy.png",
    description: "",
  },
  {
    name: "There's Something In The Water",
    file: "/water.png",
    description: "",
  },
  {
    name: "Virginia Beach Wordmark",
    file: "/vb-wordmark.png",
    description: "",
  },
  {
    name: "Try Ortho Keys",
    file: "/try-ortho-keys.png",
    description:
      "A logo for a hobby website for ortholinear mechanical keyboards.",
  },
];

export default function Logos() {
  return (
    <div className="bg-darkpurp">
      <Head>
        <title>Ian Fajardo | Lead, Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <div className="py-4">
        <div className="container text-white">
          <div className="row">
            <div className="col-lg-12">
              <h1 className="text-white">Logo Design</h1>
              <p className="lead" style={{ fontSize: "1.25rem" }}>
                Your company logo is one of the most important components to
                your brand. I will work together with you to make sure that you
                appropriately matches your company and style.
              </p>
              <hr />
            </div>
          </div>
        </div>
      </div>

      <div className="py-4">
        <div className="container">
          <div className="row ">
            {logos.map((logo, index) => (
              <div
                key={index}
                className="col-lg-4 text-white  mb-5 align-items-center"
              >
                <div className="mb-3">
                  <h4>{logo.name}</h4>
                </div>
                <img
                  className="img-fluid pb-3"
                  src={logo.file}
                  alt={logo.name}
                />
                <p>{logo.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}
